### PR TITLE
Add GaugeRelative to support Telegraf statsd implementation

### PR DESCRIPTION
**Pull request by stevenh**
Telegraf doesn't support support negative counters, requiring relative gauge values instead. This adds the new method GaugeRelative to allow for this.

### CODE REVIEW

**Review by caojia — APPROVED** [review]

**Comment by stevenh** [comment]
Any update on getting this merged?

**Comment by snusmu** [comment]
please merge this! 
it is not just telegraf issue - the official statsd docs also allow relative gauge values:
https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges

**Comment by joeycumines** [comment]
@snusmu this project is most definitely dead, but I am maintaining a backwards compatible fork.

I'll investigate these changes / relative gauge support when I get a chance.

**Comment by joeycumines** [comment]
Righto @snusmu, my fork now has relative gauge support. The current release is v1.2.0.

Diff of the changes: https://github.com/joeycumines/statsd/compare/a8e6f804b9bd5dc8504d4bda11208a85887beaa5...78fe5e2df6b2a7014b957a987672bb46c5dcaf36

I retained little of this PR/fork, and already had quite a few equivalent changes, but I did do a merge (meaning my fork is now up to date with https://github.com/multiplay/statsd).

Oddly enough, the original author did had to account for the relative stats behavior (in order to add support for negative gauge values), which makes it seem like a strange omission.

**Comment by stevenh** [comment]
Thanks @joeycumines 

@danmrichards @lwaddicor worth considering switching over to this more maintained fork?

**Comment by stevenh** [comment]
Closing this as its not maintained any more.

**Pull request closed without merging**
